# Generated by Django 5.0 on 2023-12-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('parent', 'Parent'), ('vendor', 'Vendor'), ('schoolOwner', 'SchoolOwner')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=15)),
                ('Location', models.CharField(max_length=255)),
                ('Pincode', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('FatherName', models.CharField(max_length=255)),
                ('FatherQualification', models.CharField(max_length=255)),
                ('FatherOccupation', models.CharField(max_length=255)),
                ('FatherIncome', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FatherEmail', models.EmailField(max_length=254)),
                ('MotherName', models.CharField(max_length=255)),
                ('MotherQualification', models.CharField(max_length=255)),
                ('MotherOccupation', models.CharField(max_length=255)),
                ('MotherIncome', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MotherEmail', models.EmailField(max_length=254)),
                ('roles', models.ManyToManyField(blank=True, to='user.role')),
            ],
        ),
    ]
