# Generated by Django 5.0 on 2023-12-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_roles_alter_user_table_delete_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='FatherEmail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='FatherIncome',
        ),
        migrations.RemoveField(
            model_name='user',
            name='FatherName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='FatherOccupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='FatherQualification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='MotherEmail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='MotherIncome',
        ),
        migrations.RemoveField(
            model_name='user',
            name='MotherName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='MotherOccupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='MotherQualification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Pincode',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fatherEmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='fatherIncome',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='fatherName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='fatherOccupation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='fatherQualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='motherEmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='motherIncome',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='motherName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='motherOccupation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='motherQualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
