# Generated by Django 5.0 on 2023-12-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_phone_user_phone_remove_user_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField(blank=True)),
                ('fatherName', models.CharField(blank=True, max_length=255)),
                ('fatherQualification', models.CharField(blank=True, max_length=255)),
                ('fatherOccupation', models.CharField(blank=True, max_length=255)),
                ('fatherIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('fatherEmail', models.EmailField(blank=True, max_length=254)),
                ('motherName', models.CharField(blank=True, max_length=255)),
                ('motherQualification', models.CharField(blank=True, max_length=255)),
                ('motherOccupation', models.CharField(blank=True, max_length=255)),
                ('motherIncome', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('motherEmail', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'eduUser',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
