# Generated by Django 5.0 on 2023-12-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_eduuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('starting_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('fee_upto', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('board', models.CharField(blank=True, max_length=255)),
                ('classes', models.CharField(blank=True, max_length=255)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('facilities', models.TextField(blank=True)),
                ('classification', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('strength', models.IntegerField(blank=True)),
                ('transportation', models.BooleanField(blank=True)),
                ('min_admission_age', models.IntegerField(blank=True)),
                ('reviews', models.TextField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('images', models.ImageField(blank=True, null=True, upload_to='school_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.eduuser')),
            ],
            options={
                'db_table': 'school',
            },
        ),
    ]
