# Generated by Django 5.0 on 2023-12-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='fee_upto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='min_admission_age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='school',
            name='starting_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='strength',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='transportation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('school_applied_for', models.CharField(max_length=255)),
                ('class_applied_for', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=255)),
                ('religion', models.CharField(blank=True, max_length=255)),
                ('caste', models.CharField(blank=True, max_length=255)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('class_previously_attended', models.CharField(blank=True, max_length=255)),
                ('reason_for_tc', models.TextField(blank=True)),
                ('sibling_name', models.CharField(blank=True, max_length=255)),
                ('sibling_age', models.IntegerField(blank=True, null=True)),
                ('sibling_class', models.CharField(blank=True, max_length=255)),
                ('sibling_school', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('skype', models.CharField(blank=True, max_length=255)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='birth_certificates/')),
                ('previous_marksheet', models.FileField(blank=True, null=True, upload_to='previous_marksheets/')),
                ('admission_status', models.CharField(default='pending', max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.eduuser')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
